### ISSUE TITLE
Walk-in

### ISSUE THREAD

**Issue by james31366** [3-00AM/vaccine-haven#6]
### Walk-in

**Walk-in** is the function that displays the number of people that can Walk-in to that service site and who already take the vaccine cannot use the walk-in.

Task:

- [ ] know if there are vaccines left for the current day
- [ ] the person who already get the vaccine and already book cannot walk-in

**Comment by NarawishS** [comment]
since service site decide to not implement this feature so we will close this issue

**Comment by NarawishS** [comment]
walk in is implemented by service site so we will reopen this issue
